x-airflow-common:
  &airflow-common
  build:
    context: .
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:airflow@postgres:5432/airflow
    - AIRFLOW__CORE__FERNET_KEY=
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__LOGGING_LEVEL=INFO
    - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
  volumes:
    - ../dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs

services:
    postgres:
        image: postgres:13
        container_name: airflow_postgres_test_ph
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
          - postgres-db-volume:/var/lib/postgresql/data

    airflow-init:
        << : *airflow-common
        container_name: airflow_init_test_ph
        command: db init
        restart: on-failure

    airflow-user:
        << : *airflow-common
        container_name: airflow_user_test_ph
        command: users create
            --role Admin
            --username admin
            --password admin
            --email admin@example.com
            --firstname admin
            --lastname admin
        restart: on-failure

    airflow-webserver:
        << : *airflow-common
        container_name: airflow_webserver_test_ph
        depends_on:
            - postgres
        ports:
            - "8080:8080"
        command: webserver
        restart: always

    airflow-scheduler:
        << : *airflow-common
        command: scheduler
        container_name: airflow_scheduler_test_ph
        restart: always

volumes:
  postgres-db-volume:
